#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Return,
    Literal(String),
    LiteralStartTemplate(String),
    LiteralMiddleTemplate(String),
    LiteralEndTemplate(String),
    LBrace,
    RBrace,
    LParen,
    RParen,
    Semicolon,
    Dot,
    Colon,
    Plus,
    Minus,
    Star,
    Slash,
    Var,
    Val,
    If,
    Elif,
    Else,
    Equal,
}
